[build]
  command = "npm run build"
  publish = ".next"

[functions]
  external_node_modules = ["sharp"]
  node_bundler = "esbuild"

[functions."*"]
  timeout = 120

[[plugins]]
  package = "@netlify/plugin-nextjs"
